### ISSUE TITLE
Questionnaire form doesn't save fields that were corrected before

### ISSUE THREAD

**Issue by rdonegan** [achalc/ZWPA#127]

**Comment by achalc** [comment]
does this mean when there's an error the page doesn't save the acceptable inputs?

**Comment by rdonegan** [comment]
It means that it isn't saving the "E-Wastes" or "Other Materials" fields because of "Unpermitted parameters". This is something I had fixed previously with your help, but now it suddenly isn't working again.

**Comment by rdonegan** [comment]
I think it's because someone messed with the controller. I have no idea why though.

**Comment by rdonegan** [comment]
Yep. That was it.

**Comment by achalc** [comment]
interesting. the walkthrough controller hasn't changed in about a month though

**Comment by rdonegan** [comment]
Maggie changed it in her most recent pull request. I'll submit the fix later though. I'm doing a bunch of these.
