### ISSUE TITLE
Nav bar buttons are weird for certain breakpoints

### ISSUE THREAD

**Issue by achalc** [achalc/ZWPA#145]
![screen shot 2015-04-28 at 12 10 52 pm](https://cloud.githubusercontent.com/assets/5040838/7374346/bdefe4b8-ed9f-11e4-8342-c3b6803fb2b5.png)

**Comment by achalc** [comment]
also 'no clients entered' could look better

**Comment by rdonegan** [comment]
The nav bar issue has something to do with the Foundation source code - I don't know that it can be fixed. I don't think it's a major issue though.

**Comment by achalc** [comment]
:(
